spring:
  config:
    activate:
      on-profile: "qa"

loans:
  #version: "{cipher}81142a30d008c885a326da6ea8476652f97904fc16d3cb8eabb303491034a023"
  version: "loans-2"


info:
  app:
    name: "loans qa"
    description: "loans Application qa"
    version: "1.0.0 qa"